### ISSUE TITLE
[IDEA] Armor and Hardsuits block taser projectiles

### ISSUE THREAD

**Issue by Dagreenskin** [Sierracode/-tg-station#137]
Might be an interesting shakeup of the meta. Would give disablers and lethal shots more of a use, and will lead to lenghty gunfights actually happening rather than one-shot taser spamming. Plus MUH REELISM.

**Comment by chaosyourgod** [comment]
I would say hardsuits since you're already slow in them and that's a better trade off for it, however I don't think any kinda hardsuit should do this, I would say the engineering hardsuit and make it electric proof entirely but then the sec hardsuit would be utterly disregarded for those, so I don't know I certainly think how armor is right now is fine though

**Comment by Dagreenskin** [comment]
Its not that they are electric proof, its that the electrodes from the taser cant penetrate them

**Comment by chaosyourgod** [comment]
what's the difference then?

**Comment by Sierracode** [comment]
This might actually be something I try to do, I want to lean more into little touch ups to stuns and sec ect. So changing how stuns and disablers work would actually be pretty comfy. Will have to make it so they get bullied by stun battons though. I mean it is shocking the entire suit whereas the pins from a tazer would just bounce off.

**Comment by Sierracode** [comment]
Stun update kinda removed the need for this. In the future might refer to this.
