### ISSUE TITLE
can we get actual vent crawling back?

### ISSUE THREAD

**Issue by chaosyourgod** [Sierracode/-tg-station#94]
this not teleport is real shit

**Comment by Zaers** [comment]
You can't exactly get something back if you never had it in the first place, but I remember being told to not port it because it fucked ventcrawlers that didn't resist pressure damage hard
However because I got told that ages ago, I guess it should be possible to port it and try to balance it so that ventcrawlers aren't too easily fucked over

**Comment by ZioZan** [comment]
Here are revelant pulls:
https://github.com/tgstation/tgstation/pull/9090 
Fixes:
https://github.com/tgstation/tgstation/pull/9296
https://github.com/tgstation/tgstation/pull/10690
https://github.com/tgstation/tgstation/pull/11067
https://github.com/tgstation/tgstation/pull/12459
https://github.com/tgstation/tgstation/pull/13771
https://github.com/tgstation/tgstation/pull/15177
https://github.com/tgstation/tgstation/pull/15327

**Comment by AssBlastProductions** [comment]
Doesn't look like /tg/ is having too much of a problem with it, I realize monkeys and other critters would be vulnerable to the pressure in the pipes but most of the time that I've seen the distro pressure get raised it's not been raised above 500 kpa since very few people actually put volume pumps on the distro on this and previous servers.

If it becomes a problem would it be possible to maybe just make critters and mobs that are affected by pressure have something of a grace period after entering a vent until they start being affected by the pressure or would that affect them outside of pipes as well? Other than monkeys that may be used by lings and geneticists the only other thing I can think of that could be a problem would be spider critters that crawl around vents.

**Comment by Sierracode** [comment]
Considering adding this. Does allow you to cuck an alien infestation by putting a canister full of FLAMIN HOT CO2 into the system for the one that is unfortunate enough to be in there.

**Comment by AssBlastProductions** [comment]
I think it at the very least is worth testing it and see how it goes. In the case of lings maybe their lesser form could be something other than a monkey that does resist pressure? Although that would still leave antag geneticists without a simple ventcrawling access.

**Comment by chaosyourgod** [comment]
how about a crab?

**Comment by Sierracode** [comment]
Closing to clean up issue tab. Will see if zaers wants to make this work later on in the month. Maybe after new map TM
